language: 
  - node_js

node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiter_tests

before_script:
  - psql -c 'create database waiter_tests;' -U postgres
  - psql -U postgres -d waiter_tests -a -f tables.sql

services:
  - postgresql